#!/usr/bin/env python3
"""Generates core/src/ucs_data.cpp from assets/ucs/ucs_v8.2.1.csv (extension-4 §4.1).

Output is committed so builds never need Python. Strings are emitted as plain C++ narrow
literals with every byte >= 0x80 escaped in octal (portable across MSVC source charsets),
and every literal stays far below MSVC's 16 KB single-literal limit (asserted).
"""
import csv
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSV = ROOT / "assets" / "ucs" / "ucs_v8.2.1.csv"
OUT = ROOT / "core" / "src" / "ucs_data.cpp"
COLUMNS = ["Category", "SubCategory", "CatID", "CatShort", "Explanations", "Synonyms"]


def c_literal(s: str) -> str:
    out = ['"']
    for b in s.encode("utf-8"):
        if b == 0x22:
            out.append('\\"')
        elif b == 0x5C:
            out.append("\\\\")
        elif b == 0x0A:
            out.append("\\n")
        elif b == 0x0D:
            continue
        elif b == 0x09:
            out.append(" ")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\%03o" % b)
    out.append('"')
    lit = "".join(out)
    assert len(lit) < 16000, "literal too long for MSVC"
    return lit


def main() -> int:
    with CSV.open(encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        assert reader.fieldnames == COLUMNS, reader.fieldnames
        rows = list(reader)
    cat_ids = [r["CatID"] for r in rows]
    assert len(cat_ids) == len(set(cat_ids)), "duplicate CatID"
    version = CSV.stem.split("_v")[1]
    lines = [
        "// GENERATED by tools/gen_ucs_table.py from assets/ucs/%s — do not edit." % CSV.name,
        "// Universal Category System list, public domain (see assets/ucs/PROVENANCE.md).",
        "",
        "namespace sp::ucs_data {",
        "",
        "extern const char *const kVersion;",
        "extern const unsigned kRowCount;",
        "extern const char *const kRows[][6];",
        "",
        "const char *const kVersion = %s;" % c_literal(version),
        "const unsigned kRowCount = %d;" % len(rows),
        "",
        "// Columns: Category, SubCategory, CatID, CatShort, Explanations, Synonyms (CSV order).",
        "const char *const kRows[][6] = {",
    ]
    for r in rows:
        lines.append("    {%s}," % ", ".join(c_literal(r[c].strip()) for c in COLUMNS))
    lines += ["};", "", "} // namespace sp::ucs_data", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote %s: %d rows, UCS v%s" % (OUT.relative_to(ROOT), len(rows), version))
    return 0


if __name__ == "__main__":
    sys.exit(main())
